package(default_visibility = ["//visibility:public"])

java_library(
  name = 'user',
  exports = ["@user//jar"],
)

java_library(
  name = 'dev',
  exports = ["@dev//jar"],
)

java_library(
  name = 'javax-validation',
  exports = ["@javax-validation//jar"],
)

java_library(
  name = 'jsinterop-annotations',
  exports = ["@jsinterop-annotations//jar"],
)

java_library(
  name = 'ant',
  exports = ["@ant//jar"],
)

java_library(
  name = 'colt',
  exports = ["@colt//jar"],
)

java_library(
  name = 'tapestry',
  exports = ["@tapestry//jar"],
)

java_library(
  name = 'w3c-css-sac',
  exports = ["@w3c-css-sac//jar"],
)
